# Site settings
title: Alan Foster
email: alan@alanfoster.me
description: >
  This is the blog of Alan Foster; a developer with a passion for learning new programming languages, frameworks, and paradigms.
baseurl: ""
url: "http://alanfoster.me" # the base hostname & protocol for your site
twitter_username: alanfosterdev
github_username: alanfoster

# Build settings
markdown: kramdown
