version: '3'

services:
  service:
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - "./src:/app/src"
      - "./static:/app/static"
      - "./plugins:/app/plugins"
      - "./package.json:/app/package.json"
    command: yarn develop
